language: python
python:
  - "3.6"
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "rosesthen00b-github"

sudo: required
install:  
  - sh ci/install_requirements.sh
  - pip install coveralls
  - pip install codecov

script:
     - cd ./project-cobol-fixed-format && gradle check && cd ..
     - cd ./project-cobol-free-format && gradle check && cd ..
     - cd ./project-cobol-unit-test && gradle check && cd ..
     - cd ./project-cobol-unit-test && gradle testUnit computeTestCoverage --debug --stacktrace && cd ..
     - cat ./project-cobol-unit-test/build/CobolUnit/coverage.xml

after_success:
  - coveralls
  - codecov
  - sonar-scanner -Dsonar.login=$SONAR -Dsonar.projectKey=cobol -Dsonar.organization=rosesthen00b-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io 
