language: python
python:
  - "3.6"
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "rosesthen00b-github"

sudo: required
install:  
  - sh ci/install_requirements.sh > install.log
  - pip install coveralls
  - pip install codecov

script:
  - sh ci/pull_plugin_sources.sh
  - sh ci/build_plugin.sh
  - sh ci/exec_tests.sh
  - sh ci/exec_tests.sh

after_success:
  - coveralls
  - codecov
  - sonar-scanner -Dsonar.login=$SONAR -Dsonar.projectKey=cobol -Dsonar.organization=rosesthen00b-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io 
