language: python
python:
  - "3.6"
sudo: required

jdk:
  - oraclejdk8

sudo: required
install:  
  - sh ci/install_requirements.sh
  - pip install coveralls
  - pip install codecov

script:
     - ./gradlew --version
     - ./gradlew check
     - ./gradlew project-cobol-unit-test:testUnit project-cobol-unit-test:computeTestCoverage --debug
     - cat project-cobol-unit-test/build/CobolUnit/coverage.xml

after_success:
  - coveralls
  - codecov

