language: java

jdk:
  - oraclejdk8

sudo: required
install: 
  - sh ci/install_requirements.sh


script:
     - gradle --version
     - gradle check
     - gradle project-cobol-unit-test:testUnit project-cobol-unit-test:computeTestCoverage


after_success:
  - coveralls
  - codecov
