language: python
python:
  - "3.6"
sudo: required

jdk:
  - oraclejdk8

sudo: required
install:  
  - sh ci/install_requirements.sh
  - pip install coveralls
  - pip install codecov

script:
     - gradle --version
     - gradle check
     - gradle project-cobol-unit-test:testUnit project-cobol-unit-test:computeTestCoverage


after_success:
  - coveralls
  - codecov
